testVal: true
items:
   wraith_chest:
      ==: org.bukkit.inventory.ItemStack
      type: LEATHER_CHESTPLATE
      meta:
         ==: ItemMeta
         meta-type: UNSPECIFIC
         display-name: Wraith Rags
         lore:
            - The tattered rags of a wraith
   wraith_scythe:
      ==: org.bukkit.inventory.ItemStack
      type: WOODEN_HOE
      meta:
         ==: ItemMeta
         meta-type: UNSPECIFIC
         display-name: Wraith Scythe
         lore:
            - not very sharp
   wraith_helm:
      ==: org.bukkit.inventory.ItemStack
      type: WOODEN_HOE
      meta:
         ==: ItemMeta
         meta-type: UNSPECIFIC
         display-name: Wraith Scythe
         lore:
            - not very sharp
heads:
   wraith_skull:
      itemData:
         ==: org.bukkit.inventory.ItemStack
         type: PLAYER_HEAD
         meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: Wraith Hood
            lore:
               - spooky
      texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmRhYTZhOTgzNDIxNzliNDU2ZjU2YTQ0NTM0OWM3ZWVlNmYxYTdhNTkyN2E0OTBjNDQyOTNiMGFhNzc4YmUyIn19fQ==
      dropChance: 1.0
mobs:
   wraith:
      base: WITHER_SKELETON
      chance: 0.9
      name: Wraith
      item: wraith_scythe
      helm: wraith_skull
      chest: wraith_chest
      potions:
         INVISIBILITY: 1 
         SLOWNESS: 1
       